version: '3.1'

services:
  flashcardsdb:
    image: 'postgres:13-alpine'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 1
    ports:
      - '5432:5432'
    container_name: flashcards_postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flashcards

  liquibase:
    image: 'liquibase/liquibase:4.9.1'
    container_name: liquibase
    depends_on:
      flashcardsdb:
        condition: service_healthy
    volumes:
      - ./src/main/resources/liquibase/:/liquibase/changelog/
    command: --url=jdbc:postgresql://flashcardsdb:5432/flashcards --changeLogFile=db-changelog-master.xml --username=postgres --password=postgres update

  app:
    image: 'flashcards.bot:latest'
    build:
      context: .
    container_name: pro.flashcards.bot
    depends_on:
      flashcardsdb:
        condition: service_healthy
      liquibase:
        condition: service_started
    environment:
      - FLASHCARDS_BOT_NAME=yourName
      - FLASHCARDS_BOT_TOKEN=yourToken
      - TZ=Europe/Moscow